- hosts: web
  become: yes
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "Remove nginx"
    apt:
      name: ['nginx']
      state: absent

  - name: "Remove DocumentRoot of {{ item }}"
    file:
      path: /var/www/html/{{ item }}
      state: absent
    with_items:
      - "{{ domains }}"

  - name: "Remove conf of {{ item }}"
    file:
      path: /etc/nginx/sites-enabled/{{ item }}
      state: absent
    with_items:
      - "{{ domains }}"

