- hosts: web
  become: yes
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "Install nginx"
    apt:
      name: ['nginx']
      state: latest

  - name: "Create DocumentRoot of {{ item }}"
    file:
      path: /var/www/html/{{ item }}
      state: directory
      mode: '0775'
      owner: "{{ http_user }}"
      group: "{{ http_user }}"
    with_items:
      - "{{ domains }}"

  - name: "Sync website {{ item }}"
    synchronize:
      src: files/{{ item }}
      dest: /var/www/html/{{ item }}
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    with_items:
      - "{{ domains }}"

  - name: "Copy conf {{ item }}"
    template:
      src: site.conf.j2
      dest: /etc/nginx/sites-enabled/{{ item }}
      owner: "{{ http_user }}"
      group: "{{ http_user }}"
      mode: '0644'
    with_items:
      - "{{ domains }}"


  - name: restart nginx
    service:
      name: nginx
      state: restarted
    become: true
    register: service_output

      
  - debug: var=service_output
