---
all:
  hosts:
  vars:
    ansible_user: ubuntu 
    ansible_port: 22
    ansible_ssh_private_key_file: /home/ubuntu/ansible/setupscripts/remote_pvt 
  children:
    web:
      hosts:
        172.31.8.163
    database:
      hosts:
        172.31.8.163
      vars:
        db_port: 3306


