---
all:
  hosts:
  vars:
    ansible_user: ubuntu 
    ansible_port: 22
    ansible_ssh_private_key_file: /home/ubuntu/ansible/setupscripts/remote_pvt 
  children:
    web:
      hosts:
        172.31.81.248
      vars:
        http_port: 80
        http_user: root
        domains:
          - mytestdomain1.com
          - mytestdomain2.com
          - mytestdomain3.com
    database:
      hosts:
        172.31.81.248
      vars:
        db_port: 3306


